import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ContextProvider } from "@/components/Providers/ContextProvider";
import { cn } from "@/lib/utils";
import { ClerkProvider } from '@clerk/nextjs'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    
    <html lang="en">
      <body className={cn(inter.className," overflow-x-hidden w-screen")}>
        <ContextProvider>
          <ClerkProvider>

          <div id="blob"></div>
          {children}
          </ClerkProvider>
        </ContextProvider>
      </body>
    </html>
  );
}
